### ISSUE TITLE
Be more explicit about what's happening in the require.ensure block

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-aggregate-translations#10]
I'm seeing links out to this warning (http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it) in a project that is enabling blue bird warnings.  I think we need to return null in our require.ensure.

**Comment by emilyrohrbough** [comment]
I am seeing this issue with translatiosnLoader.js as well when fallback translations are used.

**Comment by emilyrohrbough** [comment]
![Screen Shot 2019-10-01 at 3 11 18 PM](https://user-images.githubusercontent.com/14099737/65996806-c2a20400-e45d-11e9-9afa-0a592a42002b.png)
