### ISSUE TITLE
Terra-aggregate-translations does not work with react-intl 3.0.0 or higher.

### ISSUE THREAD

**Issue by gustavofulton** [cerner/terra-aggregate-translations#15]
# Issue Description

Terra-aggregate-translations does not work with react-intl 3.0.0 or higher.  It seems that react-intl v3 does not support `locale-data` anymore (can be found [here](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#migrate-to-using-native-intl-apis)), so then it can't correctly find and load the translations with `require('react-intl/locale-data/...');`.

Not sure what the roadmap is here, but thought would let you guys know. Attached is the error message displayed.

 ## Additional Context / Screenshots

<img width="1063" alt="Screen Shot 2019-10-14 at 5 12 28 PM" src="https://user-images.githubusercontent.com/10981250/66786405-d01bad00-eea5-11e9-86fb-dccaa0d44953.png">

 ## @ Mentions

Talked with @emilyrohrbough and she recommended me to open this issue here.

**Comment by bjankord** [comment]
We have a spike for react-intl v3 support: https://github.com/cerner/terra-core/issues/2406
We won't have support for react-intl v3 until we work through this spike.

**Comment by mjhenkes** [comment]
Closed, track cerner/terra-core#2406 for intl v3 support
